---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[swpr_ruby]
      - recipe[swpr_ruby::chruby]
    attributes:
      swpr_ruby:
        versions:
          - 2.2.2
          - 2.2.3
